/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_ThroughputTestService          25
#define gattdb_throughput_indications         27
#define gattdb_throughput_notifications       31
#define gattdb_transmission_on                35
#define gattdb_throughput_result              39
#define gattdb_ThroughputInformationService   42
#define gattdb_connection_phy                 44
#define gattdb_connection_interval            48
#define gattdb_responder_latency              52
#define gattdb_supervision_timeout            56
#define gattdb_pdu_size                       60
#define gattdb_mtu_size                       64

#define gattdb_generic_attribute_len          2
#define gattdb_service_changed_char_len       4
#define gattdb_database_hash_len              16
#define gattdb_client_support_features_len    1
#define gattdb_device_name_len                15
#define gattdb_device_information_len         2
#define gattdb_manufacturer_name_string_len   12
#define gattdb_model_number_string_len        10
#define gattdb_hardware_revision_string_len   5
#define gattdb_firmware_revision_string_len   8
#define gattdb_system_id_len                  8
#define gattdb_ThroughputTestService_len      16
#define gattdb_throughput_indications_len     255
#define gattdb_throughput_notifications_len   255
#define gattdb_transmission_on_len            1
#define gattdb_throughput_result_len          4
#define gattdb_ThroughputInformationService_len 16
#define gattdb_connection_phy_len             1
#define gattdb_connection_interval_len        4
#define gattdb_responder_latency_len          4
#define gattdb_supervision_timeout_len        4
#define gattdb_pdu_size_len                   1
#define gattdb_mtu_size_len                   1


#endif // __GATT_DB_H
