// WombCare TinyML inference glue.
// Feeds the 8 spec features -> standardize -> int8 quantize -> TFLite-Micro
// -> dequantize -> NSP class + confidence.
//
// -------------------------------------------------------------------------
// AI/ML SDK 3.0.0 API
// -------------------------------------------------------------------------
// This uses the unified `sl_ml_model_*` interface (the old
// `tflite_micro_model.hpp` / raw MicroInterpreter API was removed in 3.0.0).
//
// The model is added through the "ML Model" software component: import
// wombcare_nsp.tflite (reconstructed from model_data.c). The ML compiler
// then generates:
//     sl_ml_model_wombcare_nsp.h      (this include)
//     sl_ml_wombcare_nsp_model_handle (the model handle + resolver + arena)
//
// NOTE: the generated names use the .tflite file stem. If you import the model
// under a different name than "wombcare_nsp", update MODEL_HEADER / the handle
// symbol below to match (see the migration guide's <MODEL_STEM> rule).
//
// Scaler + quant params come from scaler.c. Feature values MUST follow
// FEATURE_SPEC.md (bpm units, per-minute rates).




#include <math.h>

#include "wombcare_ml.h"
#include "scaler.h"


// Generated by the ML Model component from wombcare_nsp.tflite.
#include "sl_ml_model_wombcare_nsp.h"

namespace {
// True once sl_ml_model_init() has loaded the model successfully.
bool g_ready = false;
}  // namespace

extern "C" void wombcare_ml_init(void) {
    g_ready = (sl_ml_model_init(&sl_ml_wombcare_nsp_model_handle) == SL_STATUS_OK);
}

extern "C" WombCareResult_t wombcare_ml_run(const WombCareFeatures_t *f) {
    WombCareResult_t res = {WOMBCARE_NORMAL, 0.0f, {0, 0, 0}, false};
    if (!g_ready) return res;

    TfLiteTensor *input  = sl_ml_wombcare_nsp_model_handle.input_tensor(0);
    TfLiteTensor *output = sl_ml_wombcare_nsp_model_handle.output_tensor(0);
    if (input == nullptr || output == nullptr) return res;

    // Feature vector in the FIXED spec order (== feature_order.txt / scaler order).
    const float x[WOMBCARE_N_FEATURES] = {
        f->lb_bpm,          // LB
        f->mstv_ms,         // MSTV  (bpm per spec)
        f->mltv_ms,         // MLTV  (bpm per spec)
        f->accel_count,     // AC_rate  (per-minute per spec)
        f->decel_count,     // DEC_rate (per-minute per spec)
        f->fetal_movements, // FM_rate  (per-minute per spec)
        f->mean_hr_bpm,     // MeanHR
        f->hr_variance,     // Variance (bpm^2 per spec)
    };

    // Standardize with the trained scaler, then int8-quantize into the input tensor.
    for (int i = 0; i < WOMBCARE_N_FEATURES; i++) {
        float xs = (x[i] - g_feat_mean[i]) / g_feat_std[i];
        int32_t q = (int32_t)lroundf(xs / g_in_scale) + g_in_zp;
        if (q < -128) q = -128;
        if (q > 127) q = 127;
        input->data.int8[i] = (int8_t)q;
    }

    if (sl_ml_model_run(&sl_ml_wombcare_nsp_model_handle) != SL_STATUS_OK) return res;

    // Dequantize the 3 outputs -> probabilities; argmax.
    int best = 0;
    float best_p = -1.0f;
    for (int k = 0; k < 3; k++) {
        float p = (output->data.int8[k] - g_out_zp) * g_out_scale;
        res.probs[k] = p;
        if (p > best_p) { best_p = p; best = k; }
    }
    res.nsp = (WombCareNSP_t)best;
    res.confidence = best_p;
    res.ok = true;
    return res;
}

#if WOMBCARE_ML_SELFTEST

#include "golden_vectors.h"
#include "wombcare_debug.h"

extern "C" int wombcare_ml_selftest(void) {
    int passed = 0;

    for (int i = 0; i < GOLDEN_N; i++) {
        const float *g = golden_features[i];

        // Same order as feature_order.txt / the x[] vector above.
        WombCareFeatures_t f;
        f.lb_bpm          = g[0];
        f.mstv_ms         = g[1];
        f.mltv_ms         = g[2];
        f.accel_count     = g[3];
        f.decel_count     = g[4];
        f.fetal_movements = g[5];
        f.mean_hr_bpm     = g[6];
        f.hr_variance     = g[7];

        WombCareResult_t r = wombcare_ml_run(&f);

        bool ok = r.ok && (r.nsp == (WombCareNSP_t)golden_expected_class[i]);

        for (int k = 0; k < 3; k++) {
            if (fabsf(r.probs[k] - golden_expected_prob[i][k])
                > WOMBCARE_GOLDEN_PROB_TOL) {
                ok = false;
            }
        }

        if (ok) passed++;

        // Probabilities are logged in per-mille integers: app_log is not
        // built against a float-capable printf in this project.
        WC_LOG("GOLDEN[%d] %s exp=%d got=%d p=%d/%d/%d\r\n",
               i,
               ok ? "PASS" : "FAIL",
               golden_expected_class[i],
               (int)r.nsp,
               (int)(r.probs[0] * 1000.0f),
               (int)(r.probs[1] * 1000.0f),
               (int)(r.probs[2] * 1000.0f));
    }

    WC_LOG("GOLDEN: %d/%d passed\r\n", passed, GOLDEN_N);

    return passed;
}

#endif /* WOMBCARE_ML_SELFTEST */

extern "C" const char *wombcare_ml_status_str(WombCareNSP_t nsp) {
    switch (nsp) {
        case WOMBCARE_NORMAL:     return "HEALTHY";
        case WOMBCARE_SUSPECT:    return "WATCH";
        case WOMBCARE_PATHOLOGIC: return "ALERT";
        default:                  return "UNKNOWN";
    }
}
