// Auto-generated by quantize_export.py -- do not edit.
#ifndef WOMBCARE_MODEL_DATA_H
#define WOMBCARE_MODEL_DATA_H
#include <stdint.h>
extern const unsigned char g_wombcare_model[];
extern const unsigned int g_wombcare_model_len;
#endif  // WOMBCARE_MODEL_DATA_H
