# *Licensed to the Apache Software Foundation (ASF) under one
# *or more contributor license agreements.  See the NOTICE file
# *distributed with this work for additional information
# *regarding copyright ownership.  The ASF licenses this file
# *to you under the Apache License, Version 2.0 (the
# *"License"); you may not use this file except in compliance
# *with the License.  You may obtain a copy of the License at
#
# *  http://www.apache.org/licenses/LICENSE-2.0
#
# *Unless required by applicable law or agreed to in writing,
# *software distributed under the License is distributed on an
# *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# *KIND, either express or implied.  See the License for the
# *specific language governing permissions and limitations
# *under the License.
"""Quantize to int8 TFLite-Micro and export for the EFR32MG26 (FR-ML-6).

Steps:
  1. Post-training full-integer int8 quantization with a representative dataset
     drawn from the (standardised) training features.
  2. Parity check: float Keras vs int8 TFLite on the test set -- the delta in
     ROC-AUC / sensitivity must be small (documented in reports/parity.json).
  3. Emit the model as a C array (model_data.c/.h) for TFLite-Micro / MLTK and a
     short integration note describing the inference entry point.

The firmware feeds a standardised 22-feature vector; the model returns
P(abnormal). The wellness score = 1 - P(abnormal) (see wellness.py).
"""
from __future__ import annotations

import json

import numpy as np

import config as C
from dataset import build
from features_v2 import FEATURE_NAMES_V2 as FEATURE_NAMES


def representative_dataset(Xs):
    def gen():
        for row in Xs.astype(np.float32):
            yield [row.reshape(1, -1)]
    return gen


def to_c_array(tflite_bytes: bytes, var: str = "g_wombcare_model") -> tuple[str, str]:
    hexs = ", ".join(f"0x{b:02x}" for b in tflite_bytes)
    header = f"""// Auto-generated by quantize_export.py -- do not edit.
#ifndef WOMBCARE_MODEL_DATA_H
#define WOMBCARE_MODEL_DATA_H
#include <stdint.h>
extern const unsigned char {var}[];
extern const unsigned int {var}_len;
#endif  // WOMBCARE_MODEL_DATA_H
"""
    source = f"""// Auto-generated by quantize_export.py -- do not edit.
#include "model_data.h"
const unsigned char {var}[] = {{ {hexs} }};
const unsigned int {var}_len = {len(tflite_bytes)};
"""
    return header, source


def main() -> None:
    import tensorflow as tf
    from tensorflow import keras
    from sklearn.metrics import roc_auc_score

    model = keras.models.load_model(C.ARTIFACTS_DIR / "mlp.keras")
    scaler = dict(np.load(C.ARTIFACTS_DIR / "scaler.npz", allow_pickle=True))

    # Parity is float-vs-int8 fidelity (not generalisation), so it runs on all
    # records. The deployed model is trained on all records too (train.py).
    ds = build(verbose=False)
    mean, std = scaler["mean"], scaler["std"]
    Xtr = (ds.X - mean) / std                 # representative data for int8 calibration
    Xte = (ds.X - mean) / std
    yte, gte = ds.y, ds.groups

    # --- int8 quantization ----------------------------------------------
    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = representative_dataset(Xtr)
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    tflite = conv.convert()
    (C.ARTIFACTS_DIR / "wombcare_int8.tflite").write_bytes(tflite)

    # --- run int8 model on test set -------------------------------------
    interp = tf.lite.Interpreter(model_content=tflite)
    interp.allocate_tensors()
    inp, outp = interp.get_input_details()[0], interp.get_output_details()[0]
    in_scale, in_zp = inp["quantization"]
    out_scale, out_zp = outp["quantization"]

    q_out = []
    for row in Xte.astype(np.float32):
        q = np.round(row / in_scale + in_zp).astype(np.int8).reshape(inp["shape"])
        interp.set_tensor(inp["index"], q)
        interp.invoke()
        o = interp.get_tensor(outp["index"]).astype(np.float32)
        q_out.append(float((o - out_zp) * out_scale))
    q_out = np.array(q_out)
    f_out = model.predict(Xte, verbose=0).ravel()

    def per_record(p):
        recs = sorted(set(gte))
        yr = np.array([yte[gte == r][0] for r in recs])
        pr = np.array([p[gte == r].mean() for r in recs])
        return yr, pr

    yr, f_pr = per_record(f_out)
    _, q_pr = per_record(q_out)
    parity = {
        "float_auc": round(float(roc_auc_score(yr, f_pr)), 4),
        "int8_auc": round(float(roc_auc_score(yr, q_pr)), 4),
        "mean_abs_score_delta": round(float(np.mean(np.abs(f_out - q_out))), 5),
        "max_abs_score_delta": round(float(np.max(np.abs(f_out - q_out))), 5),
        "tflite_bytes": len(tflite),
    }
    parity["auc_delta"] = round(parity["int8_auc"] - parity["float_auc"], 4)
    with open(C.REPORTS_DIR / "parity.json", "w") as fh:
        json.dump(parity, fh, indent=2)

    # --- C array + integration note -------------------------------------
    header, source = to_c_array(tflite)
    exp = C.ARTIFACTS_DIR / "firmware"
    exp.mkdir(exist_ok=True)
    (exp / "model_data.h").write_text(header)
    (exp / "model_data.c").write_text(source)
    np.savez(exp / "scaler.npz", mean=mean, std=std,
             feature_names=np.array(FEATURE_NAMES))
    (exp / "feature_order.txt").write_text("\n".join(FEATURE_NAMES) + "\n")
    (exp / "INTEGRATION.md").write_text(_integration_note(parity, in_scale, in_zp,
                                                          out_scale, out_zp))

    print(json.dumps(parity, indent=2))
    print(f"\nint8 model: {len(tflite)} bytes ({len(tflite)/1024:.1f} KB)")
    print("saved -> artifacts/wombcare_int8.tflite, artifacts/firmware/{model_data.c,.h,scaler.npz}")
    print("        reports/parity.json")


def _integration_note(parity, in_scale, in_zp, out_scale, out_zp) -> str:
    feats = "\n".join(f"  {i:2d}. {n}" for i, n in enumerate(FEATURE_NAMES))
    return f"""# WombCare model -- firmware integration note (FR-ML-6)

The MG26 runs the int8 TFLite-Micro model `g_wombcare_model` (model_data.c).

## Inference entry point (pseudocode)
```c
// 1. Compute the 22 FHR features for the current 20-min window (see feature_order.txt).
// 2. Standardise: x_std[i] = (feat[i] - mean[i]) / std[i]   // scaler.npz
// 3. Quantize:    q[i] = round(x_std[i] / {in_scale:.6g} + ({in_zp}))   // int8
// 4. Invoke the interpreter on q[] -> int8 output o.
// 5. Dequantize:  p_abnormal = (o - ({out_zp})) * {out_scale:.6g}
// 6. wellness_score = 1.0 - p_abnormal     // dashboard number, 0..1
```

## Tensors
- Input : int8[1, {len(FEATURE_NAMES)}]  scale={in_scale:.6g}  zero_point={in_zp}
- Output: int8[1, 1]                      scale={out_scale:.6g}  zero_point={out_zp}

## Feature vector order (must match exactly)
{feats}

## Quantization parity (float vs int8, per-record test set)
- Float ROC-AUC : {parity['float_auc']}
- Int8  ROC-AUC : {parity['int8_auc']}   (delta {parity['auc_delta']})
- Mean |score delta|: {parity['mean_abs_score_delta']}   Max: {parity['max_abs_score_delta']}
- Model size: {parity['tflite_bytes']} bytes
"""


if __name__ == "__main__":
    main()
